tag:
  'PPO_TD'

setup:
  seed: 1
  use_gpu: True

#simple_tag", "simple_adversary" e "simple_push
train:
  name: 'simple_tag'
  n_episodes: 2000
  max_step: 400
  verbose: 10
agent:
  update_freq: 10
  n_epochs: 10
  eps_clip: 0.2
  gamma: 0.95 # Gives the best performance in CartPole-v1/LunarLander-v2

  std: 1
  std_scale: True
  std_decay: 0.9
  std_min: 0.1

  buffer:
    batch: 256 #128

  actor:
    h_layers: 2
    h_size: 64
    print_model: False

  critic:
    h_layers: 2
    h_size: 64
    print_model: False

      

